server:
    port: 8080

spring:
    application:
        name: gateway

    cloud:
        gateway:
            server:
                webmvc:
                    routes:
                    -   id: calidades-service
                        uri: lb://calidades-service
                        predicates:
                        - Path=/api/calidades/**

                    -   id: despachos-service
                        uri: lb://despachos-service
                        predicates:
                        - Path=/api/despachos/**

                    -   id: envasados-service
                        uri: lb://envasados-service
                        predicates:
                        - Path=/api/envasados/**

                    -   id: fermentaciones-service
                        uri: lb://fermentaciones-service
                        predicates:
                        - Path=/api/fermentaciones/**

                    -   id: mantenimientos-service
                        uri: lb://mantenimientos-service
                        predicates:
                            - Path=/api/v1/mantenimientos/**

                    -   id: materiales-service
                        uri: lb://materiales-service
                        predicates:
                        - Path=/api/materiales/**

                    -   id: pedido-service
                        uri: lb://pedido-service
                        predicates:
                            - Path=/api/pedidos/**

                    -   id: producciones-service
                        uri: lb://producciones-service
                        predicates:
                            - Path=/api/producciones/**

                    -   id: recetas-service
                        uri: lb://recetas-service
                        predicates:
                            - Path=/api/recetas/**

                    -   id: stocks-service
                        uri: lb://stocks-service
                        predicates:
                            - Path=/api/stocks/**
springdoc:
    swagger-ui:
        path: /swagger-ui/index.html
        urls:
        -   name: 1. Calidades
            url: /api/calidades/v3/api-docs
        -   name: 2. Despachos
            url: /api/despachos/v3/api-docs
        -   name: 3. Envasados
            url: /api/envasados/v3/api-docs
        -   name: 4. Fermentaciones
            url: /api/fermentaciones/v3/api-docs
        -   name: 5. Mantenimientos
            url: /api/v1/mantenimientos/v3/api-docs
        -   name: 6. Materiales
            url: /api/materiales/v3/api-docs
        -   name: 7. Pedidos
            url: /api/pedidos/v3/api-docs
        -   name: 8. Producciones
            url: /api/producciones/v3/api-docs
        -   name: 9. Recetas
            url: /api/recetas/v3/api-docs
        -   name: 10. Stocks
            url: /api/stocks/v3/api-docs
    api-docs:
        enabled: true